app:
  name: ui
  image:
    repository: onecx/onecx-tenant-ui
  routing:
    enabled: true
    path: /mfe/tenant/
  operator:
    microfrontend:
      enabled: true
      spec:
        exposedModule: "./OneCXTenantModule"
        description: "OneCX Tenant UI"
        note: "OneCX OneCXTenant UI module auto import via MF operator"
    permission:
      enabled: true
      spec:
        permissions:
          TENANT:
            CREATE: Create tenant
            EDIT: Edit tenant
            DELETE: Delete tenant
            SAVE: Update and save tenant
            VIEW: View mode for tenant
            SEARCH: Seaarch tenant
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            clientId: onecx-tenant-ui
